networks:
  crosseval_network:

services:
  # Nginx Service
  nginx-server:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./CrossEval:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - crosseval_network
    mem_limit: 512m

  # MySQL Service
  mysql:
    image: mysql:5.7.34
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: CrossEval
      MYSQL_PASSWORD: CrossEval2025@
      MYSQL_ROOT_PASSWORD: CrossEval2025@
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - crosseval_network
    mem_limit: 1g

  # PHP (Laravel) Service
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./CrossEval:/var/www/html:delegated
    networks:
      - crosseval_network
    mem_limit: 512m

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - crosseval_network
    mem_limit: 256m

  # Composer Service (for dependency management)
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./CrossEval:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - crosseval_network

  # NPM (Next.js) Service (run in production mode)
  npm:
    image: node:20.14.0
    container_name: npm
    volumes:
      - ../frontend:/var/www/html
    ports:
      - 3000:3000
    working_dir: /var/www/html
    command: |
      sh -c "npm install --legacy-peer-deps && npm run build && npm run start"
    networks:
      - crosseval_network
    mem_limit: 1g

  # npm:
  #   image: node:20.14.0
  #   container_name: npm
  #   volumes:
  #     - ../FrontEnd:/var/www/html:delegated # Ensure changes sync properly
  #     - /var/www/html/node_modules # Prevents overwriting node_modules
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   working_dir: /var/www/html
  #   command: ["npm", "run", "dev"]
  #   networks:
  #     - crosseval_network

  # Artisan Service (for Laravel Artisan commands)
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./CrossEval:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - crosseval_network

  # Mailhog Service (only for development)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - crosseval_network

  # Adminer (Web interface for MySQL)
  adminer-crosseval:
    image: adminer:4.7.7-standalone
    container_name: adminer-crosseval
    ports:
      - 8080:8080
    restart: always
    networks:
      - crosseval_network
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    mem_limit: 256m